version: "3"
services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://34.53.75.59:5000
        - REACT_APP_FRONTEND_URL=http://34.53.75.59
    container_name: react-frontend
    ports:
      - "80:80"
    working_dir: /app
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: node-backend
    ports:
      - "5000:5000"
    working_dir: /app
    restart: always
    networks:
      - app-network


networks:
  app-network: